// <auto-generated />
using System;
using ApiPulseHQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPulseHQ.Infrastructure.Migrations
{
    [DbContext(typeof(ApiPulseDbContext))]
    [Migration("20260609134347_UpdateAlertRuleFields")]
    partial class UpdateAlertRuleFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertOnFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnRecovery")
                        .HasColumnType("bit");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAlertSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceEndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThresholdSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceEndpointId");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.ServiceCheckLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ServiceEndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceEndpointId");

                    b.ToTable("ServiceCheckLogs", (string)null);
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.ServiceEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceEndpoints", (string)null);
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.StatusPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StatusPages", (string)null);
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.StatusPageService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceEndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusPageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceEndpointId");

                    b.HasIndex("StatusPageId");

                    b.ToTable("StatusPageServices");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("ApiPulseHQ.Domain.Entities.ServiceEndpoint", "ServiceEndpoint")
                        .WithMany()
                        .HasForeignKey("ServiceEndpointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceEndpoint");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.ServiceCheckLog", b =>
                {
                    b.HasOne("ApiPulseHQ.Domain.Entities.ServiceEndpoint", "ServiceEndpoint")
                        .WithMany()
                        .HasForeignKey("ServiceEndpointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceEndpoint");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.ServiceEndpoint", b =>
                {
                    b.HasOne("ApiPulseHQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.StatusPage", b =>
                {
                    b.HasOne("ApiPulseHQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.StatusPageService", b =>
                {
                    b.HasOne("ApiPulseHQ.Domain.Entities.ServiceEndpoint", "ServiceEndpoint")
                        .WithMany("StatusPageServices")
                        .HasForeignKey("ServiceEndpointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiPulseHQ.Domain.Entities.StatusPage", "StatusPage")
                        .WithMany("StatusPageServices")
                        .HasForeignKey("StatusPageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceEndpoint");

                    b.Navigation("StatusPage");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.ServiceEndpoint", b =>
                {
                    b.Navigation("StatusPageServices");
                });

            modelBuilder.Entity("ApiPulseHQ.Domain.Entities.StatusPage", b =>
                {
                    b.Navigation("StatusPageServices");
                });
#pragma warning restore 612, 618
        }
    }
}
